language: c

arch:
#  - amd64
  - arm64

os:
  - linux
#  - osx

dist: xenial

compiler:
  - gcc
  - clang

env:
  matrix:
  - BUILD_SYSTEM="autotools" CONFIGURE_OPTS=
  - BUILD_SYSTEM="autotools" CONFIGURE_OPTS=--enable-64-bit-words
  - BUILD_SYSTEM="cmake"     CONFIGURE_OPTS=
  - BUILD_SYSTEM="cmake"     CONFIGURE_OPTS=-DENABLE_64_BIT_WORDS=ON

before_install:
  - CMAKE_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${CMAKE_DIR}
  - cd ${CMAKE_DIR}
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/extra/cmake-3.17.0-1-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/extra/jsoncpp-1.9.1-1-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/core/libarchive-3.4.2-1-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/extra/libuv-1.35.0-1-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/core/gcc-libs-9.2.0-4-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/extra/rhash-1.3.9-1-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/core/glibc-2.30-3-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/core/libnsl-1.2.0-2-aarch64.pkg.tar.xz;
      travis_retry wget --no-check-certificate http://mirror.archlinuxarm.org/aarch64/core/libtirpc-1.2.5-1-aarch64.pkg.tar.xz;
      tar -xvf libarchive-3.4.2-1-aarch64.pkg.tar.xz;
      tar -xvf libuv-1.35.0-1-aarch64.pkg.tar.xz;
      tar -xvf jsoncpp-1.9.1-1-aarch64.pkg.tar.xz;
      tar -xvf gcc-libs-9.2.0-4-aarch64.pkg.tar.xz;
      tar -xvf rhash-1.3.9-1-aarch64.pkg.tar.xz;
      tar -xvf glibc-2.30-3-aarch64.pkg.tar.xz;
      tar -xvf cmake-3.17.0-1-aarch64.pkg.tar.xz;
      tar -xvf libnsl-1.2.0-2-aarch64.pkg.tar.xz;
      tar -xvf libtirpc-1.2.5-1-aarch64.pkg.tar.xz;
      LD_LIBRARY_PATH=/home/ubuntu/deps/usr/lib:$LD_LIBRARY_PATH;
      PATH=${CMAKE_DIR}/usr:${CMAKE_DIR}/usr/bin:$PATH;
      cd ${TRAVIS_BUILD_DIR};
    fi
  - LD_LIBRARY_PATH=/home/ubuntu/deps/usr/lib:$LD_LIBRARY_PATH
  - PATH=${CMAKE_DIR}/usr:${CMAKE_DIR}/usr/bin:$PATH

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y install gettext libtool-bin libogg-dev doxygen libxml2-utils w3c-sgml-lib; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update ; brew install libogg; fi

script:
  - if [[ "${BUILD_SYSTEM}" == "autotools" ]]; then ./autogen.sh && ./configure $CONFIGURE_OPTS && make && make check; fi
  - if [[ "${BUILD_SYSTEM}" == "cmake" ]]; then mkdir cmake-build && cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON $CONFIGURE_OPTS && cmake --build . && ctest -V; fi
  - if [ $TRAVIS_OS_NAME = linux ] && [ ${BUILD_SYSTEM} = "autotools" ]; then
      xmllint --valid --noout doc/html/*.html;
      xmllint --valid --noout doc/html/api/*.html;
    fi
